octopus:
  environments:
    - production
  replicated: true
  fully_replicated: true 
  production:
    slave1:
      host: ip-10-182-195-244.ec2.internal
      adapter: mysql2
      database: notify
      username: root
      reconnect: true
