octopus:
  replicated: true
  fully_replicated: true 
  production:
    slave1:
      host: ec2-54-204-124-215.compute-1.amazonaws.com 
      adapter: mysql2
      database: notify
      username: root
      reconnect: true
